openapi: "3.0.0"

info:
  title: PyConJP 2020 Connexion Demo
  description: PyConJP 2020 Connexion Demo
  contact:
    name: Akira Inamori
    email: akira.inamori@tf-ebina.com
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: connexion url

paths:
  /:
    get:
      summary: API Top page
      description: Return OK message when it API is working.
      operationId: app.PyConJP.url_top
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK
  /demo/{demo_path}:
    get:
      summary: Demo programs get
      description: Call demo.py and methods
      operationId: demo.DemoClass.demo_get
      parameters:
        - $ref: '#/components/parameters/demo_path'
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK
    post:
      summary: Demo programs post
      description: Call demo.py and methods
      operationId: demo.DemoClass.demo_post
      parameters:
        - $ref: '#/components/parameters/demo_path'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_params"
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK
  /demo2/{demo_path}:
    get:
      summary: Demo programs get
      description: Call demo.py and methods
      operationId: demo.DemoClass.demo_get2
      parameters:
        - $ref: '#/components/parameters/demo_path'
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK
    post:
      summary: Demo programs post
      description: Call demo.py and methods
      operationId: demo.DemoClass.demo_post2
      parameters:
        - $ref: '#/components/parameters/demo_path'
        - $ref: '#/components/parameters/demo_path2'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_params"
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK
  /ngdemo/{demo_path}:
    get:
      summary: None classmethod Demo programs get
      description: Call demo.py and methods none classmethod
      operationId: demo.DemoClass.none_class_get
      parameters:
        - $ref: '#/components/parameters/demo_path'
      responses:
        '200':
          description: Regular response.
          content:
            text/plain:
              schema:
                type: string
              example: OK

components:
  parameters:
    demo_path:
      name: demo_path
      description: PyConJP demo path parameter
      in: path
      required: true
      schema:
        type: string
        example: sample_path
    demo_path2:
      name: demo_path2
      description: PyConJP demo path parameter
      in: query
      required: true
      schema:
        type: string
        example: sample_path
  schemas:
    post_params:
      type: object
      required:
        - name
      properties:
        name:
          type: string
